### ISSUE TITLE
Install fails with missing dependency on fusepy

### ISSUE THREAD

**Issue by benmathews** [bspaans/kubefuse#11] opened 2016-06-10 16:23 UTC
```
$ pip install kubefuse
Collecting kubefuse
  Downloading kubefuse-0.5.1.tar.gz
Building wheels for collected packages: kubefuse
  Running setup.py bdist_wheel for kubefuse ... done
  Stored in directory: /home/ben_mathews/.cache/pip/wheels/fd/52/d0/f23760eacb117fe75c496580e699f661df80e229c67ebfb2ad
Successfully built kubefuse
Installing collected packages: kubefuse
Successfully installed kubefuse-0.5.1
$ kubefuse ~/k8s
Traceback (most recent call last):
  File "/home/ben_mathews/workspace/Platform/MY_ENV/bin/kubefuse", line 7, in <module>
    from kubefuse.kubefuse import main
  File "/home/ben_mathews/workspace/Platform/MY_ENV/local/lib/python2.7/site-packages/kubefuse/kubefuse.py", line 7, in <module>
    from fuse import FUSE, FuseOSError, Operations, LoggingMixIn
ImportError: No module named fuse
```

Works after `pip install fusepy`.

**Comment by bspaans** [comment] 2016-06-16 13:42
Closing this one as it's a duplicate of #6. Will try and fix this shortly!

**Closed as completed by bspaans** 2016-06-16 13:42 UTC
